# Generated by Django 5.1 on 2025-04-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='owner',
        ),
    ]
